import "./globals.css";
import ClientHeaderWrapper from "@/components/layout/header/ClientHeaderWrapper";
import FooterNew from "@/components/layout/footer/FooterNew";
// import "bootstrap/dist/css/bootstrap.min.css";  
import { Exo_2, Inter, Open_Sans, Poppins } from "next/font/google";
import BootstrapClient from "@/components/other/BootstrapClient";

// Configure each font
const exo2 = Exo_2({
  subsets: ["latin"],
  variable: "--font-exo2",
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
  weight: ["300"],
});

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["300", "400", "500", "600", "700"],
});

// Metadata for SEO
export const metadata = {
  title: "Carrum Downs Dental Clinic",
  description: "Quality dental care for families in Carrum Downs.",
};

// ✅ Main Root Layout
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`
          ${exo2.variable} 
          ${inter.variable} 
          ${openSans.variable} 
          ${poppins.variable}
        `}
      >
        <BootstrapClient /> 
        <ClientHeaderWrapper />
        {children}
        <FooterNew />
      </body>
    </html>
  );
}


// import ClientHeaderWrapper from "@/components/layout/header/ClientHeaderWrapper";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import FooterNew from "@/components/layout/footer/FooterNew";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         <ClientHeaderWrapper />
//         {children}
//         <FooterNew />
//       </body>
//     </html>
//   );
// }
